# Generated by Django 4.0.5 on 2022-07-01 13:44

import data_recorder.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_recorder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='downtime',
            field=data_recorder.models.CustomDurationField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='est_completion_time',
            field=data_recorder.models.CustomDurationField(default=''),
        ),
    ]
