# Generated by Django 4.0.5 on 2022-06-30 21:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data_recorder', '0002_remove_post_clarify_issue_remove_post_closure_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='clarify_issue',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='closure_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='post',
            name='containment_action',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='corrective_action',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='description_of_issue',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='issue_affects_other_areas',
            field=models.CharField(choices=[('A', 'YES'), ('B', 'NO')], default='B', max_length=1),
        ),
        migrations.AddField(
            model_name='post',
            name='ncr',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='prevented_reoccurence',
            field=models.CharField(choices=[('A', 'YES'), ('B', 'NO')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='post',
            name='root_cause_of_issue',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='validation_action',
            field=models.TextField(default='', null=True),
        ),
    ]
